name: .NET Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore DotNetShowcase.Web.csproj

    - name: Build
      run: dotnet build DotNetShowcase.Web.csproj --no-restore --configuration Release

    - name: Run tests (if any)
      run: dotnet test DotNetShowcase.Web.csproj --no-build --verbosity normal || echo "No tests found"

    # Optional: Publish step (for deploying or for Blazor WASM GitHub Pages)
    # - name: Publish
    #   run: dotnet publish DotNetShowcase.Web.csproj --configuration Release --output publish
